"""Pydantic v2 schemas for AI pipeline responses.

These schemas are used both for Pydantic validation of model output and as
the source for `response_json_schema` passed to Gemini's structured output API.
"""

from pydantic import BaseModel


class FieldTemplate(BaseModel):
    """Per-field semantic template generated by Stage A."""

    field_name: str
    semantic_description: str
    # {"type": "number"|"text"|"boolean", "unit": str|null} — null when unsure.
    expected_format: dict | None = None


class TemplateGenerationResponse(BaseModel):
    """Stage A response: one FieldTemplate per annotated field, in input order."""

    fields: list[FieldTemplate]
