services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: ./apps/web/.env.local
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - worker

  worker:
    build:
      context: ./apps/worker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: ./apps/worker/.env
    volumes:
      - ./apps/worker:/app
